version: '3.8'

services:
  kivy_app:
    build: ./app
    container_name: kivy_app
    volumes:
      - ./app:/app
    networks:
      - my_network

  ai_service:
    build: ./backend/ai_service
    container_name: ai_service
    volumes:
      - ./backend/ai_service:/ai_service
    depends_on:
      - mongo
    networks:
      - my_network

  call_center:
    build: ./backend/call_center
    container_name: call_center
    volumes:
      - ./backend/call_center:/call_center
    depends_on:
      - mongo
      - redis
    networks:
      - my_network

  mongo:
    image: mongo:4.4
    container_name: mongo
    volumes:
      - mongo_data:/data/db
    networks:
      - my_network

  redis:
    image: redis:6.2
    container_name: redis
    networks:
      - my_network

volumes:
  mongo_data:

networks:
  my_network: